-- ============================================================================
-- Rumah Amal Salman Garut (RASG) — Additional Dummy Seed Data
-- ============================================================================
-- Use this script if you want to populate the dashboard with extensive data.
-- Run this AFTER the main schema.sql and seed.sql

-- Insert additional dummy members into auth.users
INSERT INTO auth.users (
  id, instance_id, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  role, confirmation_token, email_change, email_change_token_new, recovery_token
)
VALUES
  ('a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', '00000000-0000-0000-0000-000000000000', 'kesehatan@org.com', crypt('password123', gen_salt('bf')), NOW(), '{"provider": "email", "providers": ["email"]}', '{"name": "Siti Kesehatan"}', NOW(), NOW(), 'authenticated', '', '', '', ''),
  ('11111111-2222-3333-4444-555555555555', '00000000-0000-0000-0000-000000000000', 'member1@org.com', crypt('password123', gen_salt('bf')), NOW(), '{"provider": "email", "providers": ["email"]}', '{"name": "Budi Member"}', NOW(), NOW(), 'authenticated', '', '', '', ''),
  ('22222222-3333-4444-5555-666666666666', '00000000-0000-0000-0000-000000000000', 'member2@org.com', crypt('password123', gen_salt('bf')), NOW(), '{"provider": "email", "providers": ["email"]}', '{"name": "Ani Relawan"}', NOW(), NOW(), 'authenticated', '', '', '', ''),
  ('33333333-4444-5555-6666-777777777777', '00000000-0000-0000-0000-000000000000', 'member3@org.com', crypt('password123', gen_salt('bf')), NOW(), '{"provider": "email", "providers": ["email"]}', '{"name": "Doni Pasif"}', NOW(), NOW(), 'authenticated', '', '', '', ''),
  ('44444444-5555-6666-7777-888888888888', '00000000-0000-0000-0000-000000000000', 'new@org.com', crypt('password123', gen_salt('bf')), NOW(), '{"provider": "email", "providers": ["email"]}', '{"name": "Eka Baru"}', NOW(), NOW(), 'authenticated', '', '', '', '');

-- Update Profiles generated by trigger
UPDATE public.profiles SET role = 'division_admin', division = 'Kesehatan', status = 'Aktif' WHERE id = 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d';
UPDATE public.profiles SET role = 'member', division = 'HR', status = 'Aktif' WHERE id = '11111111-2222-3333-4444-555555555555';
UPDATE public.profiles SET role = 'member', division = 'Ristek', status = 'Aktif' WHERE id = '22222222-3333-4444-5555-666666666666';
UPDATE public.profiles SET role = 'member', division = 'Kesehatan', status = 'Nonaktif' WHERE id = '33333333-4444-5555-6666-777777777777';
-- new@org.com is intentionally left as 'Menunggu' status since it was just registered

-- ============================================================================
-- EVENTS
-- ============================================================================

INSERT INTO events (id, title, description, date, time, location, division, status, max_participants, created_by, attendees)
VALUES
  (
    gen_random_uuid(),
    'Pelatihan React JS Dasar',
    'Pelatihan internal divisi Ristek untuk pengenalan dasar React JS dan Vite bagi anggota baru.',
    '2026-07-20',
    '19:00',
    'Zoom Meeting',
    'Ristek',
    'Akan Datang',
    30,
    '5e884898-888e-4f05-8fb9-9685a21ff461',
    ARRAY['22222222-3333-4444-5555-666666666666'::uuid]
  ),
  (
    gen_random_uuid(),
    'Rapat Evaluasi Triwulan 1',
    'Rapat khusus untuk mengevaluasi program kerja divisi selama triwulan pertama tahun 2026.',
    '2026-03-30',
    '16:00',
    'Ruang Rapat Utama',
    'HR',
    'Selesai',
    20,
    'e1a49f50-3882-4bf1-a084-25e2cd0258d4',
    ARRAY['e1a49f50-3882-4bf1-a084-25e2cd0258d4'::uuid, '11111111-2222-3333-4444-555555555555'::uuid]
  ),
  (
    gen_random_uuid(),
    'Cek Kesehatan Gratis Warga',
    'Kegiatan lapangan untuk memberikan fasilitas cek tensi darah dan gula darah gratis bagi warga sekitar sekretariat.',
    '2026-08-15',
    '07:00',
    'Halaman Masjid Al-Ikhlas',
    'Kesehatan',
    'Akan Datang',
    15,
    'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    ARRAY[]::uuid[]
  ),
  (
    gen_random_uuid(),
    'Hackathon Internal RASG',
    'Lomba coding internal selama 24 jam untuk divisi Ristek membangun solusi aplikatif untuk RASG.',
    '2025-11-10',
    '09:00',
    'Lab Komputer',
    'Ristek',
    'Dibatalkan',
    40,
    '5e884898-888e-4f05-8fb9-9685a21ff461',
    ARRAY['22222222-3333-4444-5555-666666666666'::uuid]
  );
